- name: Configure orientdb launch script
  template:
    src=orientdb-server.sh.j2
    dest={{orientdb_path}}/bin/orientdb.sh

- name: Configure orientdb server
  template:
    src=orientdb-server-config.xml.j2
    dest={{orientdb_path}}/config/orientdb-server-config.xml

- name: Configure orientdb logger
  template:
    src=orientdb-server-log.properties.j2
    dest={{orientdb_path}}/config/orientdb-server-log.properties

- name: Install orientdb as a service
  command: 'cp {{orientdb_path}}/bin/orientdb.sh /etc/init.d/orientdb'
  notify: Start OrientDB service
